
services:
  postgres:
    image: postgres:16
    container_name: postgres-akanpay
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: akanpay-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/02-init-test-db.sql
  
volumes:
  postgres_data:
